#!/usr/bin/env bash

# Helper Functions
dcleanup(){
	docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
	docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}
del_stopped(){
	local name=$1
	local state=$(docker inspect --format "{{.State.Running}}" $name 2>/dev/null)

	if [[ "$state" == "false" ]]; then
		docker rm $name
	fi
}
dmstart(){
	VMNAME=${1:-'default'}
	docker-machine start $VMNAME
	sleep 4s 
	eval $(docker-machine env $VMNAME)
}
dmstop(){
	VMNAME=${1:-'default'}
	docker-machine stop $VMNAME
}
