#!/usr/bin/env bash

# Helper Functions
dcleanup(){
  docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
  docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}
del_stopped(){
  local name=$1
  local state=$(docker inspect --format "{{.State.Running}}" $name 2>/dev/null)

  if [[ "$state" == "false" ]]; then
    docker rm $name
  fi
}

# Docker machine
dmstart(){
  VMNAME=${1:-'default'}
  docker-machine start $VMNAME
  sleep 4s
  DOCKERENV=`docker-machine env $VMNAME`
  echo $DOCKERENV > ~/.dockerenv && source ~/.dockerenv
}
dmstop(){
  VMNAME=${1:-'default'}
  docker-machine stop $VMNAME
}
dmclear() {
  unset $(env | grep DOCKER | awk -F'=' '{print $1}' | xargs)
}

# Dev
dcreate() {
  case "$1" in
    'mail')
      docker run -d -p 1080:80 -p 1025:25 --name mailcatcher tophfr/mailcatcher
      ;;
    'redis')
      docker run --name redis -d redis
      ;;
    'mysql')
      MYSQLCONF=`cd ~/dockers/mysql && pwd`
      docker run --name mysql-data -v /var/lib/mysql busybox
      docker run --name mysql \
        -v $MYSQLCONF/conf:/etc/mysql/conf.d \
        --volumes-from mysql-data \
        -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
        -d \
        -p 3306:3306 \
        mysql:5.6
      ;;
    cf|cf10|coldfusion)
      sh ~/dockers/cf10/scripts/create
      ;;
  esac
}
ddev() {
  docker start mailcatcher mysql redis
}
dcf() {
  ddev && sleep 2 && docker start cf10
}
